#!/bin/bash

# Ensure the correct command is found:
export PATH="/home/walter/Apps/code_saturne/7.1.1/code_saturne-7.1.1/arch/Linux_x86_64/bin":$PATH

# Insert default command
cs_cmd=""
if test $# = 1; then
  if test -f $1; then
    cs_cmd=gui
  fi
elif test $# = 0; then
  cs_cmd=gui
fi

# Run command
\code_saturne $cs_cmd "$@"
