name: Embed code in README

on:
  pull:
    branches:
      - main
jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: embedding code
        uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: "base-skills/programming-rust/barba12steps/step_01.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Synchronizing file"
          no_change: "No change on file"
          silent: false
